spring:
  application:
    name: filtec
  profiles:
    active: dev
  rabbitmq:
    password: admin
    username: admin
  cloud:
    openfeign:
      okhttp:
        enabled: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false



